### ISSUE TITLE
Copy changes for decomissioning

### ISSUE THREAD

**Issue by rorads** [IATI/CSV2IATI#209]
CSV2IATI is [being decommissioned](http://www.aidtransparency.net/news/iati-publishing-tool-csv2iati-to-be-decommissioned). The landing pages and headers of the website should reflect this, and inform users of future plans.

**Comment by stevieflow** [comment]
I appreciate this isn't the domain of this issue, but it could be useful to post up a (likely) date for decommission.  I think many users will see this warning and then ask... "when?"

**Comment by rory09** [comment]
Hi Stephen, thanks for your input. 

What we've maintained in our communications so far, and what we will continue to maintain is that we won't be fully decommissioning the tool (i.e. switching it off) until every publisher has migrated successfully, hence the:

> <p><span style="color:red">PLEASE NOTE: the CSV2IATI tool is scheduled to be decomissioned.</span> The tool will <strong>not</strong> be switched off until <strong>every</strong> user has migrated to another tool. Please see <a href"http://www.aidtransparency.net/news/iati-publishing-tool-csv2iati-to-be-decommissioned">here</a> for more information, and contact <a href="mailto:support@iatistandard.org">support@iatistandard.org</a> if you have any questions, or need support with migrating.</p> 

I should also point out that this branch is meant for drafting: it hasn't and won't be deployed until we've got a fuller timeline worked up and I've consulted with the rest of my team on the phrasing, so it's best to treat the copy edits here as WIP.

Thanks,
Rory

**Comment by stevieflow** [comment]
Great - thanks for clarifying @rory09 - appreciated
